//@GeneratedCode
namespace QTChinnok.WebApi
{
    ///
    /// Generated by the generator
    ///
    partial class Program
    {
        static partial void AddServices(WebApplicationBuilder builder)
        {
            builder.Services.AddTransient<QTChinnok.Logic.Contracts.Base.IArtistsAccess, QTChinnok.Logic.Controllers.Base.ArtistsController>();
            builder.Services.AddTransient<QTChinnok.Logic.Contracts.Base.IGenresAccess, QTChinnok.Logic.Controllers.Base.GenresController>();
            builder.Services.AddTransient<QTChinnok.Logic.Contracts.Base.IMediaTypesAccess, QTChinnok.Logic.Controllers.Base.MediaTypesController>();
            builder.Services.AddTransient<QTChinnok.Logic.Contracts.App.IAlbumsAccess, QTChinnok.Logic.Controllers.App.AlbumsController>();
            builder.Services.AddTransient<QTChinnok.Logic.Contracts.App.IMusicCollectionsAccess, QTChinnok.Logic.Controllers.App.MusicCollectionsController>();
            builder.Services.AddTransient<QTChinnok.Logic.Contracts.App.ITracksAccess, QTChinnok.Logic.Controllers.App.TracksController>();
        }
    }
}
