//@GeneratedCode
namespace QTChinnok.WebApi.Controllers.App
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class AlbumsController : Controllers.GenericController<QTChinnok.Logic.Models.App.Album, QTChinnok.WebApi.Models.App.AlbumEdit, QTChinnok.WebApi.Models.App.Album>
    {
        ///
        /// Generated by the generator
        ///
        static AlbumsController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public AlbumsController(QTChinnok.Logic.Contracts.App.IAlbumsAccess<QTChinnok.Logic.Models.App.Album> other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QTChinnok.WebApi.Models.App.Album ToOutModel(QTChinnok.Logic.Models.App.Album accessModel)
        {
            var handled = false;
            var result = default(QTChinnok.WebApi.Models.App.Album);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QTChinnok.WebApi.Models.App.Album.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QTChinnok.Logic.Models.App.Album accessModel, ref QTChinnok.WebApi.Models.App.Album? outModel, ref bool handled);
        partial void AfterToOutModel(QTChinnok.WebApi.Models.App.Album outModel);
    }
}
