//@GeneratedCode
namespace QTChinnok.WebApi.Controllers.App
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class MusicCollectionsController : Controllers.GenericController<QTChinnok.Logic.Models.App.MusicCollection, QTChinnok.WebApi.Models.App.MusicCollectionEdit, QTChinnok.WebApi.Models.App.MusicCollection>
    {
        ///
        /// Generated by the generator
        ///
        static MusicCollectionsController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public MusicCollectionsController(QTChinnok.Logic.Contracts.App.IMusicCollectionsAccess<QTChinnok.Logic.Models.App.MusicCollection> other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QTChinnok.WebApi.Models.App.MusicCollection ToOutModel(QTChinnok.Logic.Models.App.MusicCollection accessModel)
        {
            var handled = false;
            var result = default(QTChinnok.WebApi.Models.App.MusicCollection);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QTChinnok.WebApi.Models.App.MusicCollection.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QTChinnok.Logic.Models.App.MusicCollection accessModel, ref QTChinnok.WebApi.Models.App.MusicCollection? outModel, ref bool handled);
        partial void AfterToOutModel(QTChinnok.WebApi.Models.App.MusicCollection outModel);
    }
}
