//@GeneratedCode
namespace QTChinnok.MvvMApp.Models.Base
{
    using System;
    ///
    /// Generated by the generator
    ///
    
    public partial class MediaType
    {
        ///
        /// Generated by the generator
        ///
        static MediaType()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public MediaType()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        
        public System.String? Name { get; set; }
        ///
        /// Generated by the generator
        ///
        public static QTChinnok.MvvMApp.Models.Base.MediaType Create()
        {
            BeforeCreate();
            var result = new QTChinnok.MvvMApp.Models.Base.MediaType();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTChinnok.MvvMApp.Models.Base.MediaType Create(object other)
        {
            BeforeCreate(other);
            var result = new QTChinnok.MvvMApp.Models.Base.MediaType();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTChinnok.MvvMApp.Models.Base.MediaType instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTChinnok.MvvMApp.Models.Base.MediaType instance, object other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.Base.MediaType other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return this.CalculateHashCode(Id, Name);
        }
    }
}
