//@GeneratedCode
namespace QTChinnok.Logic.Controllers.Base
{
    using TEntity = Entities.Base.Artist;
    using TOutModel = Models.Base.Artist;
    ///
    /// Generated by the generator
    ///
    
    public sealed partial class ArtistsController : EntitiesController<TEntity, TOutModel>, Contracts.Base.IArtistsAccess<TOutModel>
    {
        ///
        /// Generated by the generator
        ///
        static ArtistsController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public ArtistsController()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public ArtistsController(ControllerObject other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
        ///
        /// Generated by the generator
        ///
        internal override TOutModel ToModel(TEntity entity)
        {
            return new TOutModel(entity);
        }
    }
}
