//@GeneratedCode
namespace QTChinnok.Logic.Controllers.Base
{
    using TEntity = Entities.Base.MediaType;
    using TOutModel = Models.Base.MediaType;
    ///
    /// Generated by the generator
    ///
    
    public sealed partial class MediaTypesController : EntitiesController<TEntity, TOutModel>, Contracts.Base.IMediaTypesAccess<TOutModel>
    {
        ///
        /// Generated by the generator
        ///
        static MediaTypesController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public MediaTypesController()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public MediaTypesController(ControllerObject other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
        ///
        /// Generated by the generator
        ///
        internal override TOutModel ToModel(TEntity entity)
        {
            return new TOutModel(entity);
        }
    }
}
