//@GeneratedCode
namespace QTChinnok.Logic.Controllers.App
{
    using TEntity = Entities.App.MusicCollection;
    using TOutModel = Models.App.MusicCollection;
    ///
    /// Generated by the generator
    ///
    
    public sealed partial class MusicCollectionsController : EntitiesController<TEntity, TOutModel>, Contracts.App.IMusicCollectionsAccess
    {
        ///
        /// Generated by the generator
        ///
        static MusicCollectionsController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public MusicCollectionsController()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public MusicCollectionsController(ControllerObject other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
        ///
        /// Generated by the generator
        ///
        internal override TOutModel ToModel(TEntity entity)
        {
            var handled = false;
            TOutModel? result = default;
            
            BeforeToOutModel(entity, ref result, ref handled);
            if (handled == false || result == default)
            {
                result = new TOutModel(entity);
            }
            AfterToOutModel(entity, result);
            return result;
        }
        partial void BeforeToOutModel(TEntity entity, ref TOutModel? result, ref bool handled);
        partial void AfterToOutModel(TEntity entity, TOutModel result);
    }
}
