//@GeneratedCode
namespace QTChinnok.Logic.Controllers.App
{
    using TEntity = Entities.App.MusicCollection;
    using TOutModel = Models.App.MusicCollection;
    ///
    /// Generated by the generator
    ///
    
    public sealed partial class MusicCollectionsController : EntitiesController<TEntity, TOutModel>, Contracts.App.IMusicCollectionsAccess<TOutModel>
    {
        ///
        /// Generated by the generator
        ///
        static MusicCollectionsController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public MusicCollectionsController()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public MusicCollectionsController(ControllerObject other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
        ///
        /// Generated by the generator
        ///
        internal override TOutModel ToModel(TEntity entity)
        {
            return new TOutModel(entity);
        }
    }
}
