//@GeneratedCode
namespace QTChinnok.Logic.Controllers.App
{
    using TEntity = Entities.App.Track;
    using TOutModel = Models.App.Track;
    ///
    /// Generated by the generator
    ///
    
    public sealed partial class TracksController : EntitiesController<TEntity, TOutModel>, Contracts.App.ITracksAccess<TOutModel>
    {
        ///
        /// Generated by the generator
        ///
        static TracksController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public TracksController()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public TracksController(ControllerObject other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
        ///
        /// Generated by the generator
        ///
        internal override TOutModel ToModel(TEntity entity)
        {
            return new TOutModel(entity);
        }
    }
}
