//@GeneratedCode
namespace QTChinnok.WebApi.Models.Base
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class ArtistEdit
    {
        ///
        /// Generated by the generator
        ///
        static ArtistEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public ArtistEdit()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public System.String? Name { get; set; }
    }
}
