//@GeneratedCode
namespace QTChinnok.Logic.Facades.App
{
    using TOutModel = Models.App.Album;
    ///
    /// Generated by the generator
    ///
    public sealed partial class AlbumsFacade : ControllerFacade<TOutModel>, Contracts.App.IAlbumsAccess<TOutModel>
    {
        ///
        /// Generated by the generator
        ///
        static AlbumsFacade()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public AlbumsFacade()
        : base(new QTChinnok.Logic.Controllers.App.AlbumsController())
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public AlbumsFacade(FacadeObject facadeObject)
        : base(new QTChinnok.Logic.Controllers.App.AlbumsController(facadeObject.ControllerObject))
        {
            Constructing();
            
            Constructed();
        }
    }
}
