//@GeneratedCode
namespace QTChinnok.Logic.Facades.App
{
    using TOutModel = Models.App.MusicCollection;
    ///
    /// Generated by the generator
    ///
    public sealed partial class MusicCollectionsFacade : ControllerFacade<TOutModel>, Contracts.App.IMusicCollectionsAccess<TOutModel>
    {
        ///
        /// Generated by the generator
        ///
        static MusicCollectionsFacade()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public MusicCollectionsFacade()
        : base(new QTChinnok.Logic.Controllers.App.MusicCollectionsController())
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public MusicCollectionsFacade(FacadeObject facadeObject)
        : base(new QTChinnok.Logic.Controllers.App.MusicCollectionsController(facadeObject.ControllerObject))
        {
            Constructing();
            
            Constructed();
        }
    }
}
