//@GeneratedCode
namespace QTChinnok.AspMvc.Models.App
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class AlbumFilter : Models.View.IFilterModel
    {
        ///
        /// Generated by the generator
        ///
        static AlbumFilter()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public AlbumFilter()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        
        ///
        /// Generated by the generator
        ///
        public IdType? ArtistId
        { get; set; }
        
        ///
        /// Generated by the generator
        ///
        public System.String? Title
        { get; set; }
        ///
        /// Generated by the generator
        ///
        public bool HasEntityValue => ArtistId != null || Title != null;
        private bool show = true;
        ///
        /// Generated by the generator
        ///
        public bool Show => show;
        ///
        /// Generated by the generator
        ///
        public string CreateEntityPredicate()
        {
            var result = new System.Text.StringBuilder();
            
            if (ArtistId != null)
            {
                if (result.Length > 0)
                {
                    result.Append(" || ");
                }
                result.Append($"(ArtistId != null && ArtistId == {ArtistId})");
            }
            if (Title != null)
            {
                if (result.Length > 0)
                {
                    result.Append(" || ");
                }
                result.Append($"(Title != null && Title.Contains(\"{Title}\"))");
            }
            return result.ToString();
        }
        ///
        /// Generated by the generator
        ///
        public override string ToString()
        {
            System.Text.StringBuilder sb = new();
            if (ArtistId != null)
{
sb.Append($"ArtistId: {ArtistId} ");
}
if (string.IsNullOrEmpty(Title) == false)
{
sb.Append($"Title: {Title} ");
}
            return sb.ToString();
        }
    }
}
