//@GeneratedCode
namespace QTChinnok.Logic.Contracts.Base
{
    using TOutModel = Models.Base.Artist;
    ///
    /// Generated by the generator
    ///
    public partial interface IArtistsAccess : Contracts.IDataAccess<TOutModel>
    {
    }
}
