//@GeneratedCode
namespace QTChinnok.Logic.Contracts.Base
{
    using TOutModel = Models.Base.Genre;
    ///
    /// Generated by the generator
    ///
    public partial interface IGenresAccess : Contracts.IDataAccess<TOutModel>
    {
    }
}
