//@GeneratedCode
namespace QTChinnok.Logic.Contracts.Base
{
    using TOutModel = Models.Base.MediaType;
    ///
    /// Generated by the generator
    ///
    public partial interface IMediaTypesAccess : Contracts.IDataAccess<TOutModel>
    {
    }
}
