//@GeneratedCode
namespace QTChinnok.Logic.Contracts.Base
{
    ///
    /// Generated by the generator
    ///
    public partial interface IMediaTypesAccess<T> : Contracts.IDataAccess<T>
    {
    }
}
