//@GeneratedCode
namespace QTChinnok.WebApi.Controllers.Base
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class GenresController : Controllers.GenericController<QTChinnok.Logic.Models.Base.Genre, QTChinnok.WebApi.Models.Base.GenreEdit, QTChinnok.WebApi.Models.Base.Genre>
    {
        ///
        /// Generated by the generator
        ///
        static GenresController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public GenresController(QTChinnok.Logic.Contracts.Base.IGenresAccess<QTChinnok.Logic.Models.Base.Genre> other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QTChinnok.WebApi.Models.Base.Genre ToOutModel(QTChinnok.Logic.Models.Base.Genre accessModel)
        {
            var handled = false;
            var result = default(QTChinnok.WebApi.Models.Base.Genre);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QTChinnok.WebApi.Models.Base.Genre.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QTChinnok.Logic.Models.Base.Genre accessModel, ref QTChinnok.WebApi.Models.Base.Genre? outModel, ref bool handled);
        partial void AfterToOutModel(QTChinnok.WebApi.Models.Base.Genre outModel);
    }
}
