//@GeneratedCode
namespace QTChinnok.WebApi.Controllers.Base
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class MediaTypesController : Controllers.GenericController<QTChinnok.Logic.Models.Base.MediaType, QTChinnok.WebApi.Models.Base.MediaTypeEdit, QTChinnok.WebApi.Models.Base.MediaType>
    {
        ///
        /// Generated by the generator
        ///
        static MediaTypesController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public MediaTypesController(QTChinnok.Logic.Contracts.Base.IMediaTypesAccess<QTChinnok.Logic.Models.Base.MediaType> other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QTChinnok.WebApi.Models.Base.MediaType ToOutModel(QTChinnok.Logic.Models.Base.MediaType accessModel)
        {
            var handled = false;
            var result = default(QTChinnok.WebApi.Models.Base.MediaType);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QTChinnok.WebApi.Models.Base.MediaType.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QTChinnok.Logic.Models.Base.MediaType accessModel, ref QTChinnok.WebApi.Models.Base.MediaType? outModel, ref bool handled);
        partial void AfterToOutModel(QTChinnok.WebApi.Models.Base.MediaType outModel);
    }
}
