//@GeneratedCode
namespace QTChinnok.Logic.Facades.Base
{
    using TOutModel = Models.Base.Genre;
    ///
    /// Generated by the generator
    ///
    public sealed partial class GenresFacade : ControllerFacade<TOutModel>, Contracts.Base.IGenresAccess<TOutModel>
    {
        ///
        /// Generated by the generator
        ///
        static GenresFacade()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public GenresFacade()
        : base(new QTChinnok.Logic.Controllers.Base.GenresController())
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public GenresFacade(FacadeObject facadeObject)
        : base(new QTChinnok.Logic.Controllers.Base.GenresController(facadeObject.ControllerObject))
        {
            Constructing();
            
            Constructed();
        }
    }
}
