//@GeneratedCode
namespace QTChinnok.Logic.Facades.Base
{
    using TOutModel = Models.Base.MediaType;
    ///
    /// Generated by the generator
    ///
    public sealed partial class MediaTypesFacade : ControllerFacade<TOutModel>, Contracts.Base.IMediaTypesAccess<TOutModel>
    {
        ///
        /// Generated by the generator
        ///
        static MediaTypesFacade()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public MediaTypesFacade()
        : base(new QTChinnok.Logic.Controllers.Base.MediaTypesController())
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public MediaTypesFacade(FacadeObject facadeObject)
        : base(new QTChinnok.Logic.Controllers.Base.MediaTypesController(facadeObject.ControllerObject))
        {
            Constructing();
            
            Constructed();
        }
    }
}
