//@GeneratedCode
namespace QTChinnok.MvvMApp.Models.App
{
    using System;
    ///
    /// Generated by the generator
    ///
    
    public partial class Track
    {
        ///
        /// Generated by the generator
        ///
        static Track()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public Track()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        
        public IdType? AlbumId { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public IdType? GenreId { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public IdType MediaTypeId { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.String Name { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        
        public System.String? Composer { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.Int32 Milliseconds { get; set; }
        ///
        /// Generated by the generator
        ///
        
        public System.Decimal UnitPrice { get; set; }
        ///
        /// Generated by the generator
        ///
        public static QTChinnok.MvvMApp.Models.App.Track Create()
        {
            BeforeCreate();
            var result = new QTChinnok.MvvMApp.Models.App.Track();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTChinnok.MvvMApp.Models.App.Track Create(object other)
        {
            BeforeCreate(other);
            var result = new QTChinnok.MvvMApp.Models.App.Track();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTChinnok.MvvMApp.Models.App.Track instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTChinnok.MvvMApp.Models.App.Track instance, object other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.App.Track other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return this.CalculateHashCode(Id, AlbumId, GenreId, MediaTypeId, Name, Composer, Milliseconds, UnitPrice);
        }
    }
}
