//@GeneratedCode
namespace QTChinnok.AspMvc.Controllers.Base
{
    using Microsoft.AspNetCore.Mvc;
    using TAccessModel = QTChinnok.Logic.Models.Base.Genre;
    using TViewModel = QTChinnok.AspMvc.Models.Base.Genre;
    using TFilterModel = QTChinnok.AspMvc.Models.Base.GenreFilter;
    using TAccessContract = QTChinnok.Logic.Contracts.Base.IGenresAccess<QTChinnok.Logic.Models.Base.Genre>;
    ///
    /// Generated by the generator
    ///
    public sealed partial class GenresController : Controllers.FilterGenericController<TAccessModel, TViewModel, TFilterModel, TAccessContract>
    {
        ///
        /// Generated by the generator
        ///
        static GenresController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        protected override string ControllerName => "Genres";
        ///
        /// Generated by the generator
        ///
        public GenresController(QTChinnok.Logic.Contracts.Base.IGenresAccess<TAccessModel> other)
        : base(other)
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override TViewModel ToViewModel(TAccessModel accessModel, ActionMode actionMode)
        {
            var handled = false;
            var result = default(TViewModel);
            BeforeToViewModel(accessModel, actionMode, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = TViewModel.Create(accessModel);
            }
            AfterToViewModel(result, actionMode);
            return BeforeView(result, actionMode);
        }
        partial void BeforeToViewModel(TAccessModel accessModel, ActionMode actionMode, ref TViewModel? viewModel, ref bool handled);
        partial void AfterToViewModel(TViewModel viewModel, ActionMode actionMode);
    }
}
