//@GeneratedCode
namespace QTChinnok.Logic.Contracts.App
{
    ///
    /// Generated by the generator
    ///
    public partial interface IMusicCollectionsAccess<T> : Contracts.IDataAccess<T>
    {
    }
}
