//@GeneratedCode
namespace QTChinnok.Logic.Contracts.App
{
    using TOutModel = Models.App.Track;
    ///
    /// Generated by the generator
    ///
    public partial interface ITracksAccess : Contracts.IDataAccess<TOutModel>
    {
    }
}
