//@GeneratedCode
namespace QTChinnok.WebApi.Models.App
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class AlbumEdit
    {
        ///
        /// Generated by the generator
        ///
        static AlbumEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public AlbumEdit()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public IdType ArtistId { get; set; }
        ///
        /// Generated by the generator
        ///
        public System.String Title { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        public QTChinnok.WebApi.Models.Base.Artist? Artist { get; set; }
    }
}
