//@GeneratedCode
namespace QTChinnok.WebApi.Models.App
{
    using System;
    ///
    /// Generated by the generator
    ///
    
    public partial class MusicCollection
    {
        ///
        /// Generated by the generator
        ///
        static MusicCollection()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public MusicCollection()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        
        public System.String Name { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        
        public System.Collections.Generic.List<QTChinnok.WebApi.Models.App.Album> Albums { get; set; } = new();
        ///
        /// Generated by the generator
        ///
        public static QTChinnok.WebApi.Models.App.MusicCollection Create()
        {
            BeforeCreate();
            var result = new QTChinnok.WebApi.Models.App.MusicCollection();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTChinnok.WebApi.Models.App.MusicCollection Create(object other)
        {
            BeforeCreate(other);
            var result = new QTChinnok.WebApi.Models.App.MusicCollection();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTChinnok.WebApi.Models.App.MusicCollection instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTChinnok.WebApi.Models.App.MusicCollection instance, object other);
        ///
        /// Generated by the generator
        ///
        public static QTChinnok.WebApi.Models.App.MusicCollection Create(QTChinnok.Logic.Models.App.MusicCollection other)
        {
            BeforeCreate(other);
            var result = new QTChinnok.WebApi.Models.App.MusicCollection();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate(QTChinnok.Logic.Models.App.MusicCollection other);
        static partial void AfterCreate(QTChinnok.WebApi.Models.App.MusicCollection instance, QTChinnok.Logic.Models.App.MusicCollection other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTChinnok.Logic.Models.App.MusicCollection other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Id = other.Id;
                Name = other.Name;
                Albums = other.Albums.Select(e => QTChinnok.WebApi.Models.App.Album.Create((object)e)).ToList();
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTChinnok.Logic.Models.App.MusicCollection other, ref bool handled);
        partial void AfterCopyProperties(QTChinnok.Logic.Models.App.MusicCollection other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTChinnok.WebApi.Models.App.MusicCollection other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Id = other.Id;
                Name = other.Name;
                Albums = other.Albums.Select(e => QTChinnok.WebApi.Models.App.Album.Create((object)e)).ToList();
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTChinnok.WebApi.Models.App.MusicCollection other, ref bool handled);
        partial void AfterCopyProperties(QTChinnok.WebApi.Models.App.MusicCollection other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.App.MusicCollection other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return this.CalculateHashCode(Id, Name, Albums);
        }
    }
}
