//@GeneratedCode
namespace QTChinnok.WebApi.Models.App
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class MusicCollectionEdit
    {
        ///
        /// Generated by the generator
        ///
        static MusicCollectionEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public MusicCollectionEdit()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public System.String Name { get; set; } = string.Empty;
    }
}
