//@GeneratedCode
namespace QTChinnok.WebApi.Models.App
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class TrackEdit
    {
        ///
        /// Generated by the generator
        ///
        static TrackEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public TrackEdit()
        {
            Constructing();
            
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public IdType? AlbumId { get; set; }
        ///
        /// Generated by the generator
        ///
        public IdType? GenreId { get; set; }
        ///
        /// Generated by the generator
        ///
        public IdType MediaTypeId { get; set; }
        ///
        /// Generated by the generator
        ///
        public System.String Name { get; set; } = string.Empty;
        ///
        /// Generated by the generator
        ///
        public System.String? Composer { get; set; }
        ///
        /// Generated by the generator
        ///
        public System.Int32 Milliseconds { get; set; }
        ///
        /// Generated by the generator
        ///
        public System.Decimal UnitPrice { get; set; }
    }
}
