//@GeneratedCode
namespace QTChinnok.Logic.Models.App
{
    ///
    /// Generated by the generator
    ///
    public partial class Album
    {
        ///
        /// Generated by the generator
        ///
        static Album()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        
        ///
        /// Generated by the generator
        ///
        public Album()
        {
            Constructing();
            _source = new Entities.App.Album();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        internal Album(Entities.App.Album source)
        {
            Constructing();
            _source = source;
            Constructed();
        }
        
        new internal Entities.App.Album Source
        {
            get => (Entities.App.Album)(_source ??= new Entities.App.Album());
            set => _source = value;
        }
        
        public IdType ArtistId
        {
            get => Source.ArtistId;
            set => Source.ArtistId = value;
        }
        
        public System.String Title
        {
            get => Source.Title;
            set => Source.Title = value;
        }
        
        public QTChinnok.Logic.Models.Base.Artist? Artist
        {
            get => Source.Artist != null ? QTChinnok.Logic.Models.Base.Artist.Create(Source.Artist) : null;
            set => Source.Artist = value?.Source;
        }
        
        public System.Collections.Generic.IList<QTChinnok.Logic.Models.App.Track> Tracks
        {
            get => new CommonBase.Modules.Collection.DelegateList<QTChinnok.Logic.Entities.App.Track, QTChinnok.Logic.Models.App.Track>(Source.Tracks, e => QTChinnok.Logic.Models.App.Track.Create(e));
        }
        
        public System.Collections.Generic.IList<QTChinnok.Logic.Models.App.MusicCollection> MusicCollections
        {
            get => new CommonBase.Modules.Collection.DelegateList<QTChinnok.Logic.Entities.App.MusicCollection, QTChinnok.Logic.Models.App.MusicCollection>(Source.MusicCollections, e => QTChinnok.Logic.Models.App.MusicCollection.Create(e));
        }
        ///
        /// Generated by the generator
        ///
        internal void CopyProperties(Entities.App.Album other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Id = other.Id;
                ArtistId = other.ArtistId;
                Title = other.Title;
                Artist = other.Artist != null ? QTChinnok.Logic.Models.Base.Artist.Create((object)other.Artist) : null;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(Entities.App.Album other, ref bool handled);
        partial void AfterCopyProperties(Entities.App.Album other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QTChinnok.Logic.Models.App.Album other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Id = other.Id;
                ArtistId = other.ArtistId;
                Title = other.Title;
                Artist = other.Artist != null ? QTChinnok.Logic.Models.Base.Artist.Create((object)other.Artist) : null;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QTChinnok.Logic.Models.App.Album other, ref bool handled);
        partial void AfterCopyProperties(QTChinnok.Logic.Models.App.Album other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.App.Album other)
            {
                result = Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return this.CalculateHashCode(Id, ArtistId, Title, Artist, Tracks, MusicCollections);
        }
        ///
        /// Generated by the generator
        ///
        public static QTChinnok.Logic.Models.App.Album Create()
        {
            BeforeCreate();
            var result = new QTChinnok.Logic.Models.App.Album();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTChinnok.Logic.Models.App.Album Create(object other)
        {
            BeforeCreate(other);
            var result = new QTChinnok.Logic.Models.App.Album();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTChinnok.Logic.Models.App.Album Create(QTChinnok.Logic.Models.App.Album other)
        {
            BeforeCreate(other);
            var result = new QTChinnok.Logic.Models.App.Album();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QTChinnok.Logic.Models.App.Album Create(Entities.App.Album other)
        {
            BeforeCreate(other);
            var result = new QTChinnok.Logic.Models.App.Album();
            result.Source = other;
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QTChinnok.Logic.Models.App.Album instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QTChinnok.Logic.Models.App.Album instance, object other);
        static partial void BeforeCreate(QTChinnok.Logic.Models.App.Album other);
        static partial void AfterCreate(QTChinnok.Logic.Models.App.Album instance, QTChinnok.Logic.Models.App.Album other);
        static partial void BeforeCreate(Entities.App.Album other);
        static partial void AfterCreate(QTChinnok.Logic.Models.App.Album instance, Entities.App.Album other);
    }
}
